version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/codingcam
      - JWT_SECRET=codingcam_jwt_secret_token_please_change_in_production
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: 